import * as pdfjs from './vendor/pdf.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.min.mjs',import.meta.url).href;
const C=window.BudgetCore,E=window.BudgetExcel,$=id=>document.getElementById(id),KEY='budget_v2';
const categories=['Élelmiszer','Vásárlás','Előfizetés','Közlekedés és szállítás','Vendéglátás','Lakhatás','Egészség','Banki díjak','Egyéb','Bevétel','Visszatérítés','Belső pénzmozgás'];
const categoryPalette=['#ff9f43','#f5c66f','#e2763f','#bd8358','#8f735f','#dfad82'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let state={version:2,transactions:[],subscriptions:[],budgets:{},dismissed:[],imports:[]},pending=null,page=0,storageBroken=false;
function notify(s,ok=false){$('notice').textContent=s;$('notice').className=ok?'success':'';}
try{const raw=localStorage.getItem(KEY);if(raw){const value=JSON.parse(raw);validateState(value);state=value;}}catch(e){storageBroken=true;notify('A mentett adatok nem olvashatók. Az eredeti tárolást nem írjuk felül. Állíts vissza egy ellenőrzött JSON-mentést. '+e.message);}
function validateState(s){if(s.version!==2||!Array.isArray(s.transactions)||!Array.isArray(s.subscriptions)||!s.budgets||!Array.isArray(s.dismissed)||!Array.isArray(s.imports))throw Error('Nem támogatott mentés.');const ids=new Set();for(const t of s.transactions){C.date(t.date);if(!t.id||ids.has(t.id)||typeof t.desc!=='string'||typeof t.category!=='string'||!Number.isFinite(t.amount)||!['HUF','EUR'].includes(t.currency))throw Error('Hibás tranzakció.');ids.add(t.id);}for(const s1 of s.subscriptions){C.date(s1.next);if(!s1.id||typeof s1.name!=='string'||!Number.isFinite(s1.amount)||s1.amount<=0||!['monthly','weekly','yearly'].includes(s1.cycle)||!['active','paused','cancelled'].includes(s1.status)||!['HUF','EUR'].includes(s1.currency))throw Error('Hibás előfizetés.');}}
function commit(next){if(storageBroken){notify('Előbb állíts vissza érvényes mentést.');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));state=next;render();return true;}catch(e){notify('Nem sikerült menteni. Lehet, hogy megtelt vagy tiltott a böngésző tárhelye. Exportáld az adataidat.');return false;}}
function mutate(fn){const next=structuredClone(state);fn(next);return commit(next);}
const fmt=(n,c=$('currency').value)=>new Intl.NumberFormat('hu-HU',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
function opts(values,selected,all){return (all?'<option value="">'+all+'</option>':'')+values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v)}</option>`).join('');}
function base(){return state.transactions.filter(t=>(!$('month').value||t.date.startsWith($('month').value))&&t.currency===$('currency').value&&(!$('account').value||t.account===$('account').value));}
function filtered(){const q=C.norm($('search').value);return base().filter(t=>(!$('categoryFilter').value||t.category===$('categoryFilter').value)&&C.norm(t.desc+' '+t.category+' '+t.account).includes(q)).sort((a,b)=>b.date.localeCompare(a.date));}
function render(){const selected=$('month').value,account=$('account').value;$('month').innerHTML=opts([...new Set(state.transactions.map(t=>t.date.slice(0,7)))].sort().reverse(),selected,'Összes hónap');$('account').innerHTML=opts([...new Set(state.transactions.map(t=>t.account||'Kézi'))].sort(),account,'Minden számla');const cats=[...new Set([...categories,...state.transactions.map(t=>t.category)])];$('categoryFilter').innerHTML=opts(cats,$('categoryFilter').value,'Minden kategória');$('editCategory').innerHTML=opts(cats,$('editCategory').value||'Egyéb');
 const ts=base(),spend=ts.filter(t=>t.category!=='Belső pénzmozgás'),expense=C.round(spend.reduce((s,t)=>s+Math.max(0,-t.amount),0)),income=C.round(spend.reduce((s,t)=>s+Math.max(0,t.amount),0));$('expense').textContent=fmt(expense);$('income').textContent=fmt(income);$('net').textContent=fmt(income-expense);
 const groups={};for(const t of spend.filter(t=>t.amount<0))groups[t.category]=(groups[t.category]||0)-t.amount;const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]);$('categories').innerHTML=renderCategoryChart(entries,expense);
 $('transferInfo').textContent=`${ts.filter(t=>t.category==='Belső pénzmozgás').length} belső pénzmozgás kihagyva a költésekből.`;
 const key=budgetKey(),limit=state.budgets[key];$('budgetAmount').value=limit??'';$('budgetAmount').disabled=!$('month').value;$('budgetForm').querySelector('button').disabled=!$('month').value;$('budgetInfo').textContent=!$('month').value?'Válassz egy hónapot a keret beállításához.':limit===undefined?'Mennyi fér bele ebben a hónapban?':expense>limit?`${fmt(expense-limit)} a kereten felül`:`Még ${fmt(limit-expense)} a keretből`;$('budgetBar').style.width=limit?Math.min(100,expense/limit*100)+'%':(expense&&limit===0?'100%':'0%');$('budgetBar').style.background=limit!==undefined&&expense>limit?'#ff8968':'#efa15b';
 renderTransactions();renderSubscriptions();}
function budgetKey(){return [$('month').value,$('currency').value,$('account').value].join('|');}
function renderCategoryChart(entries,total){
 if(!entries.length)return '<div class="empty">Még nincs költés ebben a nézetben.<br>Olvasd be az első kivonatodat.</div>';
 const top=entries.slice(0,5).map(([name,value])=>({name,value})),other=entries.slice(5).reduce((sum,[,value])=>sum+value,0),slices=other>0?[...top,{name:'Többi kategória',value:other}]:top;
 let offset=0;
 const arcs=slices.map((slice,index)=>{const share=total?slice.value/total*100:0,start=offset;offset+=share;return `<circle class="donut-slice" cx="60" cy="60" r="48" pathLength="100" fill="none" stroke="${categoryPalette[index]}" stroke-width="19" stroke-dasharray="${share.toFixed(4)} ${(100-share).toFixed(4)}" stroke-dashoffset="${(-start).toFixed(4)}"><title>${esc(slice.name)}: ${esc(fmt(slice.value))} (${share.toFixed(1)}%)</title></circle>`;}).join('');
 const legend=slices.map((slice,index)=>{const share=total?slice.value/total*100:0;return `<button class="category-legend-row" type="button" data-category-view="${esc(slice.name==='Többi kategória'?'':slice.name)}" ${slice.name==='Többi kategória'?'disabled':''}><span class="category-rank">${index+1}</span><span class="category-dot" style="--category-color:${categoryPalette[index]}"></span><span class="category-name">${esc(slice.name)}</span><strong>${share.toFixed(1)}%</strong><small>${esc(fmt(slice.value))}</small></button>`;}).join('');
 const bars=entries.map(([name,value],index)=>{const share=total?value/total*100:0,color=categoryPalette[Math.min(index,categoryPalette.length-1)];return `<button class="bar-row" type="button" data-category-view="${esc(name)}"><span><i style="--category-color:${color}"></i>${esc(name)}</span><strong>${share.toFixed(1)}% · ${esc(fmt(value))}</strong><span class="track" aria-hidden="true"><span style="width:${share}%;--category-color:${color}"></span></span></button>`;}).join('');
 return `<div class="category-summary"><div class="donut-wrap"><svg class="donut" viewBox="0 0 120 120" role="img" aria-label="Kiadások kategóriánkénti megoszlása"><circle class="donut-base" cx="60" cy="60" r="48" pathLength="100" fill="none" stroke-width="19"></circle>${arcs}</svg><div class="donut-center"><span>Összes kiadás</span><strong>${esc(fmt(total))}</strong></div></div><div class="category-legend" aria-label="Legnagyobb kiadási kategóriák">${legend}</div></div><div class="category-bars"><p class="eyebrow">MINDEN KATEGÓRIA</p>${bars}</div><p class="category-hint">Kattints egy kategóriára a hozzá tartozó tranzakciók megnyitásához.</p>`;
}
function renderTransactions(){const ts=filtered();page=Math.max(0,Math.min(page,Math.ceil(ts.length/40)-1));$('txCount').textContent=ts.length+' tétel';$('transactionRows').innerHTML=ts.slice(page*40,page*40+40).map(t=>`<tr><td>${esc(t.date)}<small>${t.page?esc(t.page)+'. forrásoldal':''}</small></td><td>${esc(t.desc)}<small>${esc(t.account)}${t.source?' · '+esc(t.source):''}${t.amountHuf!==undefined?' · '+esc(fmt(t.amountHuf,'HUF'))+' kivonati ellenérték':''}</small></td><td><select aria-label="Kategória: ${esc(t.desc)}" data-category="${esc(t.id)}">${opts([...new Set([...categories,t.category])],t.category)}</select></td><td class="right ${t.amount<0?'negative':'positive'}">${esc(fmt(t.amount,t.currency))}</td><td><button class="quiet" data-edit="${esc(t.id)}" aria-label="Szerkesztés: ${esc(t.desc)}">✎</button><button class="quiet danger" data-delete="${esc(t.id)}" aria-label="Törlés: ${esc(t.desc)}">×</button></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">Nincs a szűrésnek megfelelő tranzakció.</div></td></tr>';$('pageInfo').textContent=ts.length?`${page+1} / ${Math.ceil(ts.length/40)} oldal`:'0 tétel';$('prevPage').disabled=page===0;$('nextPage').disabled=(page+1)*40>=ts.length;}
function nextDate(iso,cycle){const d=new Date(iso+'T12:00:00Z'),day=d.getUTCDate();if(cycle==='weekly')d.setUTCDate(day+7);else{d.setUTCDate(1);if(cycle==='yearly')d.setUTCFullYear(d.getUTCFullYear()+1);else d.setUTCMonth(d.getUTCMonth()+1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));}return d.toISOString().slice(0,10);}
function suggestions(){const groups=new Map();for(const t of state.transactions){if(t.amount>=0||t.category==='Belső pénzmozgás')continue;const k=C.norm(t.desc)+'|'+t.currency;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t);}const result=[];for(const [k,ts]of groups){if(state.dismissed.includes(k)||state.subscriptions.some(s=>C.norm(s.name)+'|'+s.currency===k))continue;ts.sort((a,b)=>a.date.localeCompare(b.date));const months=new Set(ts.map(t=>t.date.slice(0,7)));const amounts=ts.map(t=>Math.abs(t.amount));const stable=Math.max(...amounts)/Math.min(...amounts)<1.1;const gaps=ts.slice(1).map((t,i)=>(new Date(t.date)-new Date(ts[i].date))/86400000);const monthly=gaps.length>=2&&gaps.every(g=>g>=24&&g<=38);if(C.subscriptionPattern.test(ts.at(-1).desc)||(months.size>=3&&stable&&monthly))result.push({key:k,t:ts.at(-1),count:ts.length});}return result;}
function renderSubscriptions(){const cur=$('currency').value,subs=state.subscriptions.filter(s=>s.currency===cur),sum=subs.filter(s=>s.status==='active').reduce((v,s)=>v+s.amount*(s.cycle==='yearly'?1/12:s.cycle==='weekly'?52/12:1),0);$('subscriptionTotal').textContent=fmt(sum)+' / hó';const sug=suggestions().filter(s=>s.t.currency===cur);$('suggestions').innerHTML=sug.map((s,i)=>`<div class="suggestion"><div><strong>${esc(s.t.desc)}</strong> · ${esc(fmt(-s.t.amount,s.t.currency))}<br><small>${s.count} korábbi terhelés · utolsó: ${esc(s.t.date)} · ellenőrizendő javaslat</small></div><div><button data-suggestion="${i}">Beállítás</button><button class="quiet" data-dismiss="${i}">Elvetés</button></div></div>`).join('');$('suggestions').onclick=e=>{const a=e.target.closest('[data-suggestion]'),b=e.target.closest('[data-dismiss]');if(a){const s=sug[Number(a.dataset.suggestion)];fillSub({name:s.t.desc,amount:-s.t.amount,currency:s.t.currency,cycle:'monthly',next:nextDate(s.t.date,'monthly')});}if(b)mutate(n=>n.dismissed.push(sug[Number(b.dataset.dismiss)].key));};
 $('subscriptionList').innerHTML=subs.map(s=>{const days=Math.ceil((new Date(s.next+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000),status={active:'Aktív',paused:'Szüneteltetett',cancelled:'Lemondottnak jelölt'}[s.status],due=s.status==='active'?(days<0?'Elmúlt dátum – ellenőrizd':days===0?'Ma esedékes':days<=7?`${days} napon belül`:'Következő terhelés'):status;return `<div class="subscription"><div><strong>${esc(s.name)}</strong><small>${esc(due)} · ${esc(s.next)} · ${esc(status)}</small></div><div><strong>${esc(fmt(s.amount,s.currency))}</strong><small>${{monthly:'havonta',yearly:'évente',weekly:'hetente'}[s.cycle]}</small></div><div class="subscription-actions"><button data-subedit="${esc(s.id)}">Szerkesztés</button><button data-subpaid="${esc(s.id)}">Dátum előre</button><button data-substatus="${esc(s.id)}">${s.status==='active'?'Szüneteltetés':'Aktiválás'}</button><button data-subcancel="${esc(s.id)}">Lemondottnak jelölés</button><button data-subdelete="${esc(s.id)}" class="danger">Törlés</button></div></div>`;}).join('')||'<div class="empty">Még nincs megerősített előfizetés ebben a pénznemben.</div>';}
function fillSub(s,focus=true){$('subId').value=s.id||'';$('subName').value=s.name||'';$('subAmount').value=s.amount||'';$('subCurrency').value=s.currency||$('currency').value;$('subCycle').value=s.cycle||'monthly';$('subNext').value=s.next||today();if(focus)$('subName').focus();}
$('subCancel').onclick=()=>fillSub({});$('subscriptionForm').onsubmit=e=>{e.preventDefault();const id=$('subId').value||uid(),old=state.subscriptions.find(s=>s.id===id),s={id,name:$('subName').value.trim(),amount:Number($('subAmount').value),currency:$('subCurrency').value,cycle:$('subCycle').value,next:C.date($('subNext').value),status:old?.status||'active'};if(!s.name||s.amount<=0||!Number.isFinite(s.amount))return;if(mutate(n=>{n.subscriptions=n.subscriptions.filter(x=>x.id!==id);n.subscriptions.push(s);})){fillSub({});notify('Előfizetés elmentve.',true);}};
$('subscriptionList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const [action,id]=Object.entries(b.dataset)[0],s=state.subscriptions.find(s=>s.id===id);if(!s)return;if(action==='subedit')return fillSub(s);if(action==='subdelete'&&!confirm('Törlöd ezt az előfizetés-nyilvántartást?'))return;mutate(n=>{const t=n.subscriptions.find(s=>s.id===id);if(action==='subpaid')t.next=nextDate(t.next,t.cycle);if(action==='substatus')t.status=t.status==='active'?'paused':'active';if(action==='subcancel')t.status='cancelled';if(action==='subdelete')n.subscriptions=n.subscriptions.filter(s=>s.id!==id);});};
$('budgetForm').onsubmit=e=>{e.preventDefault();if(!$('month').value)return;const val=Number($('budgetAmount').value);if(Number.isFinite(val)&&val>=0)mutate(n=>n.budgets[budgetKey()]=val);};
for(const id of ['month','currency','account','categoryFilter'])$(id).onchange=()=>{page=0;render();};$('search').oninput=()=>{page=0;renderTransactions();};$('prevPage').onclick=()=>{page--;renderTransactions();};$('nextPage').onclick=()=>{page++;renderTransactions();};
$('categories').onclick=e=>{const button=e.target.closest('[data-category-view]');if(!button||button.disabled)return;$('categoryFilter').value=button.dataset.categoryView;page=0;renderTransactions();location.hash='transactions';};
$('transactionRows').onchange=e=>{const id=e.target.dataset.category;if(id)mutate(n=>n.transactions.find(t=>t.id===id).category=e.target.value);};
function edit(t={}){$('editId').value=t.id||'';$('editDate').value=t.date||today();$('editDesc').value=t.desc||'';$('editAmount').value=t.amount??'';$('editCurrency').value=t.currency||$('currency').value;$('editCategory').value=t.category||'Egyéb';$('editTitle').textContent=t.id?'Tranzakció szerkesztése':'Új kézi tétel';$('editDialog').showModal();}
$('addTransaction').onclick=()=>edit();$('closeDialog').onclick=()=>$('editDialog').close();$('transactionRows').onclick=e=>{const a=e.target.closest('[data-edit]'),b=e.target.closest('[data-delete]');if(a)edit(state.transactions.find(t=>t.id===a.dataset.edit));if(b&&confirm('Törlöd ezt a tranzakciót?'))mutate(n=>n.transactions=n.transactions.filter(t=>t.id!==b.dataset.delete));};
$('transactionForm').onsubmit=e=>{e.preventDefault();const id=$('editId').value||uid(),old=state.transactions.find(t=>t.id===id),t={...old,id,date:C.date($('editDate').value),desc:$('editDesc').value.trim(),amount:Number($('editAmount').value),currency:$('editCurrency').value,category:$('editCategory').value,account:old?.account||'Kézi',bank:old?.bank||'Kézi'};if(!t.desc||!Number.isFinite(t.amount))return;if(old&&(old.amount!==t.amount||old.currency!==t.currency||old.date!==t.date)){delete t.balance;delete t.amountHuf;t.reference='';t.bookingDate=t.date;t.edited=true;}if(mutate(n=>{n.transactions=n.transactions.filter(t=>t.id!==id);n.transactions.push(t);}))$('editDialog').close();};
async function hash(buffer){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))].map(x=>x.toString(16).padStart(2,'0')).join('');}
$('fileInput').onchange=async e=>{pending=null;$('preview').hidden=true;const files=[...e.target.files];if(!files.length)return;e.target.disabled=true;const batch={transactions:[],errors:[],checks:[],hashes:[],files:[]};try{for(const file of files){notify('Feldolgozás: '+file.name);if(file.size>35*1024*1024){batch.errors.push(file.name+': túl nagy fájl (maximum 35 MB).');continue;}const buffer=await file.arrayBuffer(),fingerprint=await hash(buffer);if(state.imports.includes(fingerprint)||batch.hashes.includes(fingerprint)){batch.checks.push({label:file.name+': korábban már importált fájl, kihagyva',ok:true});continue;}let r;if(/\.pdf$/i.test(file.name)){const doc=await pdfjs.getDocument({data:buffer,useSystemFonts:true,isEvalSupported:false}).promise,pages=[];try{for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),text=await p.getTextContent();pages.push(text.items.filter(i=>i.str?.trim()).map(i=>({text:i.str,x:i.transform[4],y:p.view[3]-i.transform[5]})));}r=C.parsePDF(pages);}finally{await doc.destroy();}}else{r=E.read(XLSX.read(buffer,{type:'array',cellDates:false}),XLSX);}batch.hashes.push(fingerprint);batch.files.push(file.name);batch.transactions.push(...r.transactions.map(t=>({...t,id:uid(),source:t.source||file.name})));batch.errors.push(...r.errors.map(s=>file.name+': '+s));batch.checks.push(...r.checks.map(c=>({...c,label:file.name+' · '+c.label})));}pending=batch;showPreview();notify(batch.errors.length?'Az import ellenőrzési hibákat talált. Mentés nem történt.':'Az előnézet elkészült. Ellenőrizd, majd mentsd a tételeket.',!batch.errors.length);}catch(err){notify('Beolvasási hiba: '+err.message+'. Nem mentettünk új adatot.');}finally{e.target.disabled=false;e.target.value='';}};
function showPreview(){const merged=C.merge(state.transactions,pending.transactions);pending.added=merged.added;$('preview').hidden=false;$('preview').innerHTML=`<h3>Import-előnézet · ${pending.transactions.length} beolvasott tétel</h3><p class="small">${merged.added.length} új tétel · ${merged.duplicates} már szereplő tétel kihagyva. A pénznemeket külön kezeljük.</p>${pending.checks.map(c=>`<div class="check ${c.ok?'positive':'negative'}">${c.ok?'✓':'!'} ${esc(c.label)}${c.actual!==undefined?' · '+esc(c.actual)+' / '+esc(c.expected):''}</div>`).join('')}${pending.errors.map(e=>`<p class="negative small">${esc(e)}</p>`).join('')}<div class="table-wrap"><table><thead><tr><th>Dátum</th><th>Leírás</th><th>Kategória</th><th>Összeg</th></tr></thead><tbody>${pending.transactions.map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.desc)}<small>${esc(t.bank)} · ${esc(t.page||'')} ${t.page?'oldal':''}</small></td><td>${esc(t.category)}</td><td class="right">${esc(fmt(t.amount,t.currency))}</td></tr>`).join('')}</tbody></table></div><p><button id="confirmImport" class="primary" ${pending.errors.length||!pending.hashes.length?'disabled':''}>${merged.added.length} új tétel mentése</button> <button id="cancelImport">Mégse</button></p>`;$('confirmImport').onclick=()=>{if(!pending||pending.errors.length)return;const n=C.merge(state.transactions,pending.transactions).added;if(mutate(s=>{s.transactions.push(...n);s.imports.push(...pending.hashes);})){pending=null;$('preview').hidden=true;notify(`${n.length} új tétel elmentve.`,true);}};$('cancelImport').onclick=()=>{pending=null;$('preview').hidden=true;};}
function download(name,text){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('backup').onclick=()=>download('penzugyeim-'+today()+'.json',JSON.stringify(state,null,2));
$('restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const n=JSON.parse(await f.text());validateState(n);if(confirm(`A mentés ${n.transactions.length} tranzakciót és ${n.subscriptions.length} előfizetést tartalmaz. Lecseréled a jelenlegi adatokat?`)){const was=storageBroken;storageBroken=false;if(!commit(n))storageBroken=was;else{pending=null;$('preview').hidden=true;notify('Biztonsági mentés visszaállítva.',true);}}}catch(err){notify('Visszaállítási hiba: '+err.message);}finally{e.target.value='';}};
$('exportAll').onclick=()=>XLSX.writeFile(E.build(state.transactions,state.subscriptions,XLSX),'penzugyeim-'+today()+'.xlsx');$('exportFiltered').onclick=()=>XLSX.writeFile(E.build(filtered(),null,XLSX),'szurt-tranzakciok-'+today()+'.xlsx');$('template').onclick=()=>XLSX.writeFile(E.build([],null,XLSX),'import-sablon.xlsx');
$('clear').onclick=()=>{if(confirm('Minden v2 tranzakció, előfizetés és keret törlődik. Készíts előbb JSON-mentést! Biztosan folytatod?')){if(commit({version:2,transactions:[],subscriptions:[],budgets:{},dismissed:[],imports:[]})){pending=null;$('preview').hidden=true;}}};
try{const old=JSON.parse(localStorage.getItem('budget_transactions')||'[]');if(Array.isArray(old)&&old.length){$('legacy').hidden=false;$('legacy').innerHTML=`A korábbi verzióban ${old.length} tétel található. Ezek összege hibás lehet, ezért nem kerültek automatikusan az új kimutatásba. Az eredeti adatok megmaradtak. Olvasd be újra a kivonatokat. <button id="legacyDownload">Régi adatok letöltése</button>`;$('legacyDownload').onclick=()=>download('korabbi-tranzakciok.json',JSON.stringify(old,null,2));}}catch{notify('A régi tranzakciólista sérült; az eredeti tárolást változatlanul hagytuk.');}
render();fillSub({},false);

